{% set data = load_setup_py_data() %}

package:
  name: xarray-hdf
  version: {{ data.get('version') }}

source:
  git_url: "../"

build:
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps -vv . 

requirements:
  host:
    - python
    - pip
  run:
    - python
    - h5py
    - pandas
    - pytables
    - xarray

test:
  imports:
    - xarrayhdf
  requires:
    - pytest
  source_files:
    - test
  commands:
    - pytest

about:
  home: {{ data.get('url') }}
  license: {{ data.get('license') }}
  summary: {{ data.get('description') }}
